# Test values file for generating all of the yaml and check that
# the rendering is correct

ingress:
  enabled: true

metrics:
  enabled: true

config: |
  test_configuration

redis:
  enabled: false
externalRedis:
  password: test

postgresql:
  enabled: false
externalDatabase:
  password: test


