{{- if (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.password }}
  airflow-password: {{ .Values.auth.password | b64enc | quote }}
  {{ else if (not .Values.auth.forcePassword) }}
  airflow-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  airflow-password: {{ required "An Airflow Password is required!" .Values.auth.password }}
  {{- end }}
  {{- if .Values.auth.fernetKey }}
  airflow-fernetKey: {{ .Values.auth.fernetKey | b64enc | quote }}
  {{ else if (not .Values.auth.forcePassword) }}
  airflow-fernetKey: {{ randAlphaNum 32 | b64enc | b64enc | quote }}
  {{ else }}
  airflow-fernetKey: {{ required "An Airflow Fernet Key is required!" .Values.auth.fernetKey }}
  {{- end }}
  {{- if .Values.auth.secretKey }}
  airflow-secretKey: {{ .Values.auth.secretKey | b64enc | quote }}
  {{ else if (not .Values.auth.forcePassword) }}
  airflow-secretKey: {{ randAlphaNum 32 | b64enc | b64enc | quote }}
  {{ else }}
  airflow-secretKey: {{ required "An Airflow Secret Key is required!" .Values.auth.secretKey }}
  {{- end }}
{{- end }}
