apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-astronomer
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/camposvinicius/gcp-etl
    targetRevision: HEAD
    path: k8s/charts/airflow/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow-astronomer
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true