apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-bitnami
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts
    targetRevision: HEAD
    path: bitnami/airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true