{{- if and .Values.worker.autoscaling.enabled (or (eq .Values.executor "CeleryExecutor") (eq .Values.executor "CeleryKubernetesExecutor")) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" . }}-worker
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: worker
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "common.names.fullname" . }}-worker
  minReplicas: {{ .Values.worker.autoscaling.replicas.min }}
  maxReplicas: {{ .Values.worker.autoscaling.replicas.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.worker.autoscaling.targets.cpu }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.worker.autoscaling.targets.memory }}
{{- end }}
